### ISSUE TITLE
Gsonsupport intercepts receive pipeline when the content-type is Application/Json

### ISSUE THREAD

**Issue by Hai-Lin** [Kotlin/ktor#148]
I am trying to use the latest release of 0.4 and found the GsonSupport quick convenient. But it also intercepts receive pipeline when content-type set to Application/Json. The GSONSupport is a application level setting and how can I use different registerTypeAdapter for different URL?  I am also using Location feature, is there any way I can pass in the data class in the Location level? 

Reference code in Gsonsupport is [here](https://github.com/Kotlin/ktor/blob/bc83c3d0b6f18649606e9d535f8e4a9bb07329b1/ktor-features/ktor-gson/src/org/jetbrains/ktor/gson/GsonSupport.kt#L24).

**Comment by pzmrzy** [comment]
Same issue to me, how should I fix it?

**Comment by orangy** [comment]
Can you register all type adapters for an application and then just exchange typed data?

**Comment by Hai-Lin** [comment]
Can you provide more detail? @orangy, how do we exchange typed data?

**Comment by orangy** [comment]
Say, you have something like `Article` and `Comment` classes that you want to send and receive as JSON. You may register all required adapters in the installation script:
```
install(GsonSupport) {
    registerTypeAdapter(…) // for Article
    registerTypeAdapter(…) // for Comment
}
```
After that you can `respond<Article>` and `respond<Comment>` and receive them without thinking about it in the business logic. 

Also consider using https://github.com/SalomonBrys/Kotson for some DSLs. Since receiver in an install script is `GsonBuilder` you can directly use typed wrappers from Kotson.

**Comment by orangy** [comment]
Do you have anything else on this topic I can help you with? Did it resolve your issue?

**Comment by Hai-Lin** [comment]
@orangy  yeah thanks for the help.
