### ISSUE TITLE
Posted parameters do not work in Kweet sample app (and mine...)

### ISSUE THREAD

**Issue by schleinzer** [Kotlin/ktor#190]
Hi,

I assume, POSTed parameters are also supported when using the location API?

But, unfortunately, they do not work in my project...

So I cloned the current ktor repository and tried the kweet sample app. When calling the "register" page and posting my data (using current version of Firefox on Windows 10), they also do not work there.

"displayName", "password", etc. are all empty (default in the data class), and not filled with the actual post parameters.

Am I doing something wrong or has 0.4.x been broken somehow in this regard?

Thank you!

**Comment by orangy** [comment]
> I assume, POSTed parameters are also supported when using the location API?
That was an unfortunate consequence of treating all parameters (query or post) in the same way. This was fixed and post parameters should now be received explicitly. It makes sense, because location is a _round trip entity_, like you can handle it and you can generate an URL from it, which should hit the same handler. With POST parameters it is impossible.

We will fix sample, thanks for pointing it out.

**Comment by lbensaad** [comment]
I started testing Ktor today and I confirm that kweet is not working, please show us how to fix it, i want to progress.

**Comment by orangy** [comment]
Samples fixed

**Comment by LEFrost** [comment]
If use @Location ,At the same time, this route needs post method to solve. 
I can only use the post of io.ktor.routing.post, but it feels weird
